service: diceBot 

provider:
  name: aws
  runtime: python3.7
  region: us-west-2


functions:
  rollDice:
    handler: handler.rollTheBones
    events:
      - http:
          path: rollDice
          method: get
  showHistogram:
    handler: handler.showHistogram
    events:
        - http:
            path: showHistogram
            method: get
package:
  include:
    - src/handler.py
    - src/rollDice.py
  exclude:
    - env/**
    - hello/**
    - README.md
